include ../defaults.mk
SOURCES=AdaptationSet.cpp BasicCMParser.cpp IsoffMainManager.cpp MPD.cpp Period.cpp SegmentBase.cpp SegmentInfo.cpp BasicCMManager.cpp Group.cpp IsoffMainParser.cpp MPDManagerFactory.cpp Representation.cpp Segment.cpp SegmentList.cpp
include ../sublibs.mk
